### ISSUE TITLE
Can't Turn God Mode Off

### ISSUE THREAD

**Issue by RW5** [ForgeEssentials/ForgeEssentials#2020]
I've tried everything. /god off RW2, I've tried it all caps, all lowercase, everything (RW2 is my player name). I've dropped myself and tried to die and nothing. I've gone into survival and still nothing. It makes PVP a lot less fun with my friends. I've set the difficulty to hard and nothing. How do I fix this? I can't turn god mode off.

**Comment by luacs1998** [comment]
Try doing it manually - `/p user RW2 clear fe.protection.damageby.*`

**Comment by RW5** [comment]
How would I do that? Do I just do it in-game or do I do it in the server console?

**Comment by luacs1998** [comment]
The command I gave you is from in-game.

**Comment by MisterJenssen** [comment]
I encountered the same issue in forgeessentials-1.7.10-1.4.4 build 1160.
The console gave me this message: Player %@ not found. playername will be used, but may be inaccurate.
Deleting godmode manually with the above command dit work.

**Comment by spacebuilder2020** [comment]
This has been fixed with  #2080

There was an error in the default god script.

**Comment by Liqueseous** [comment]
Updated to the latest release and I still can't get god mode to disable.

**Comment by spacebuilder2020** [comment]
You have to let the script regenerate cause the one you have is bugged.

**Comment by Zethalion** [comment]
N/A in 1.12.2

**Comment by spacebuilder2020** [comment]
This has not been applicable in any version since the JSscripting update as the god command no longer exists.
