### ISSUE TITLE
[1.12.2]Inconsistent Vanish

### ISSUE THREAD

**Issue by DyliiLogii** [ForgeEssentials/ForgeEssentials#2369]
Vanish appears to be inconsistent between players. If entering vanish outside of the loaded chunks of another player(I believe), they will be able to see you. This is most noticeable for me If I am in vanish and then teleport away from a player and then back. Consistently reproducible. I am willing to provide anymore needed information.

**Comment by Zethalion** [comment]
In FE for 1.12.2 vanish serves no purpose anymore. Use /gamemode spectator instead. Is your issue solved with this solution?

**Comment by DyliiLogii** [comment]
This doesn’t solve my issue because, I may be wrong but, being in spectator does not allow you to build/destroy/worldedit.

**Comment by spacebuilder2020** [comment]
World Edit should work unless Spectator mode prevents you from running commands
(Though you will need to use //pos1 and //pos2)

**Comment by DyliiLogii** [comment]
Although that is true, it doesn’t solve my problem. I guess I’ll just have my staff using lots of repeated /vanish ‘s unless some type of fix is able to come of this.

**Comment by spacebuilder2020** [comment]
I am currently working on a fix that is targeted for the next release.  As a additional note, vanish is broken on all current versions of FE.

**Comment by spacebuilder2020** [comment]
@DyliiLogii Vanish should be fixed in build 14.  Please let me know if this is the case or not.

**Comment by Zethalion** [comment]
Verified it's working with build 15. Closing
